# version: '3.9'

networks:
  nd_frontend:
  nd_backend:

services:
  db:
    image: netdisco/netdisco:${NETDISCO_VERSION}-postgresql
    networks:
      - nd_backend
    restart: unless-stopped
    volumes:
      - ${PWD}/files/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 

  nd-backend:
    depends_on:
      - db
    image: "stelliferrous/netdisco:${NETDISCO_VERSION}-weekly"
    # image: "ndbuild"
    # volumes:
    #   - ${PWD}/deployment.stub.yml:/deployment.stub.yml
    networks:
      - nd_backend
    restart: unless-stopped
    environment:
      END: "backend"
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: db

  nd-frontend:
    depends_on:
      - db
      - nd-backend
    image: "stelliferrous/netdisco:${NETDISCO_VERSION}-weekly"
    # image: "ndbuild"
    # volumes:
    #   - ${PWD}/deployment.stub.yml:/deployment.stub.yml
    networks:
      - nd_frontend
      - nd_backend
    restart: unless-stopped
    environment:
      END: "frontend"
      NETDISCO_DOMAIN: discover
      NETDISCO_DB_HOST: db
    ports:
      - 5000:5000
    

