database:
{% if exists("/nd/db/name") %}
  name: '{{ getv("/nd/db/name") }}'
{% else %}
  name: 'netdisco'
{% endif %}
{% if exists("/nd/db/user") %}
  user: '{{ getv("/nd/db/user") }}'
{% else %}
  user: 'netdisco'
{% endif %}
{% if exists("/nd/db/pass") %}
  pass: '{{ getv("/nd/db/pass") }}'
{% else %}
  pass: 'netdisco'
{% endif %}
{% if exists("/nd/db/host") %}
  host: '{{ getv("/nd/db/host") }}'
{% else %}
  host: 'db'
{% endif %}

site_local_files: true

{% if exists("/nd/docker/no/auth") %}
  no_auth: {{ getv("/nd/docker/no/auth") }}
{% else %}
  no_auth: true
{% endif %}

{% if exists("/nd/domain/suffix") %}
  domain_suffix: ['{{ getv("/nd/domain/suffix") }}']
{% endif %}

