name: Weekly Build

on:
  # once a week build a new image: At 02:30 on Monday.
  schedule:
    - cron: "30 2 * * 1"
  # or manually
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Get latest release version of netdisco
      id: version
      run: |
        VERSION=$(curl -s https://api.github.com/repos/netdisco/netdisco/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Latest version is $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  docker-build:
    needs: pre-build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: nd-base
          platforms: linux/amd64
          push: true
          tags: |
            stelliferrous/netdisco:latest
            stelliferrous/netdisco:${{ needs.pre-build.outputs.version }}
          build-args: |
            VERSION=${{ needs.pre-build.outputs.version }}
